#!/usr/bin/bash

# Generated by Kimi Chat

# 遍历当前目录及子目录下的所有 .mlir 文件
find . -type f -name "hom_*.mlir" | while read mlir_file; do

    pattern="hom_linear_([0-9]+)_([0-9]+)_([0-9]+)\.mlir"

    if [[ $mlir_file =~ $pattern ]]; then
        M="${BASH_REMATCH[1]}"
        N="${BASH_REMATCH[2]}"
        K="${BASH_REMATCH[3]}"

        # 输出提取的值
        echo "M: $M, N: $N, K: $K"
    fi

    bash ./run_fp16.sh $mlir_file

done

echo "Compilation process completed for all matching files."
